### ISSUE TITLE
Compilation Error due to gettid function.

### ISSUE THREAD

**Issue by gatoWololo** [dettrace/dettrace#268]
On:
```bash
gatowololo@thinkpad ~> lsb_release -a
Description:	Ubuntu 19.10
gatowololo@thinkpad ~> uname -a
Linux thinkpad 5.3.0-40-generic #32-Ubuntu SMP Fri Jan 31 20:24:34 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux
```
Dettrace fails to compile with the error:
```bash
src/tempfile.cpp:67:14: error: static declaration of 'gettid' follows non-static declaration
static pid_t gettid(void) { return syscall(SYS_gettid); }
             ^
/usr/include/x86_64-linux-gnu/bits/unistd_ext.h:34:16: note: previous declaration is here
extern __pid_t gettid (void) __THROW;
               ^
1 error generated.
make[1]: *** [Makefile:73: src/tempfile.o] Error 1
```

We try to declare `gettid` but on my system it is already declared. I'm assuming I can't just get rid of the declaration since _some_ setup will not build without this declaration? I figured I could trivially fix this with a `#ifndef` but it doesn't seem to work.

**Comment by wangbj** [comment]
It seems like the newer glibc in ubuntu 19.10 declared `gettid`, we can add ``__attribute__((weak))`` to our definition if you need a fast work around. Just removing `static` should also work because glibc allows user to override glibc functions as I remembered.

**Comment by gatoWololo** [comment]
I see. Adding:
```C
// include/tempfile.hpp
pid_t gettid(void);
```
and
```C
// src/tempfile.cpp
pid_t gettid(void) __THROW {
  return syscall(SYS_gettid);
}
```
Fixes the error, but I'm not sure if this would be backwards compatible with older libcs. If this is correct I'd like to submit it as a pull request so other people don't immediately get an error when trying to compile it. Thoughts?

**Comment by wangbj** [comment]
Sounds good to me. no matter glibc have `gettid` or not, having a `gettid` function implementation shouldn't be an issue, at least not when creating executables.
